create table if not exists author
(
    id                int auto_increment
        primary key,
    author_full_name  varchar(255) null,
    info_about_author varchar(255) null
);

create table if not exists information
(
    id                   int auto_increment
        primary key,
    achievements         varchar(255) null,
    alias                varchar(255) null,
    attitude_to_marriage varchar(255) null,
    awards               varchar(255) null,
    biography            varchar(255) null,
    characteristic       varchar(255) null,
    citizenship          varchar(255) null,
    confession           varchar(255) null,
    country_birth        varchar(255) null,
    country_death        varchar(255) null,
    date_birth           date         null,
    date_death           date         null,
    education            varchar(255) null,
    ethnos               varchar(255) null,
    faith                varchar(255) null,
    first_name           varchar(255) not null,
    friends_and_enemies  varchar(255) null,
    last_name            varchar(255) not null,
    links_to_website     varchar(255) null,
    member_ship          varchar(255) null,
    nationality          varchar(255) null,
    occupation           varchar(255) null,
    patronymic           varchar(255) null,
    place_birth          varchar(255) null,
    place_burial         varchar(255) null,
    politic              varchar(255) null,
    profession           varchar(255) null,
    region_birth         varchar(255) null
);

create table if not exists bibliography
(
    id               int auto_increment
        primary key,
    authors          varchar(255) null,
    number_pages     int          null,
    publication_date date         null,
    work_info        varchar(255) not null,
    work_kind        varchar(255) null,
    work_name        varchar(255) null,
    information_id   int          not null,
    constraint FKohfsc4l49eu7ua5li5b70ofny
        foreign key (information_id) references information (id)
);

create table if not exists chronology
(
    id              int auto_increment
        primary key,
    date            date         null,
    event           varchar(255) not null,
    kind_chronology varchar(255) null,
    information_id  int          not null,
    constraint FKarliqsrh9j3k6aq50o4o8anu7
        foreign key (information_id) references information (id)
);

create table if not exists education
(
    id                int auto_increment
        primary key,
    activity          varchar(255) null,
    country           varchar(255) null,
    date_begin        date         null,
    date_end          date         null,
    kind_education    varchar(255) null,
    science_school    varchar(255) null,
    university        varchar(255) not null,
    work_in_specialty varchar(255) null,
    information_id    int          not null,
    constraint FKcjnjoxnogl9jvjs5aal3t3sq7
        foreign key (information_id) references information (id)
);

create table if not exists photo_archive
(
    id             int auto_increment
        primary key,
    date           date         null,
    info           varchar(255) null,
    path_picture   varchar(255) not null,
    information_id int          not null,
    constraint FKq2de1p4xdig5bflkx1206asso
        foreign key (information_id) references information (id)
);

create table if not exists quotation_type
(
    id        int auto_increment
        primary key,
    type_name varchar(255) not null
);

create table if not exists quotation
(
    dtype             varchar(31)  not null,
    id                int auto_increment
        primary key,
    date              date         null,
    domain_quotation  varchar(255) null,
    quotation         varchar(255) not null,
    work              varchar(255) null,
    information_id    int          not null,
    author_id         int          null,
    quotation_type_id int          not null,
    constraint FK5h6h8bugx192ks9v499l3u8d4
        foreign key (author_id) references author (id),
    constraint FK8w88igmjk6kumsb5t3gm7pdrd
        foreign key (information_id) references information (id),
    constraint FKosmytcdmlfojt19a0jmhtmkox
        foreign key (quotation_type_id) references quotation_type (id)
);

create table if not exists relatives
(
    id             int auto_increment
        primary key,
    date_birth     date         null,
    date_death     date         null,
    full_name      varchar(255) not null,
    info           varchar(255) null,
    relation       varchar(255) null,
    information_id int          not null,
    constraint FK3j8iamqaaofe0dhsn8jrg4qqv
        foreign key (information_id) references information (id)
);

create table if not exists reviews
(
    id             int auto_increment
        primary key,
    date_reviews   date         null,
    kind_review    varchar(255) null,
    review         varchar(255) not null,
    author_id      int          null,
    information_id int          not null,
    constraint FK8dgia41wnxqesesr9ns5aa90x
        foreign key (author_id) references author (id),
    constraint FKeyupiha7menr5ts1h3k9a9bc5
        foreign key (information_id) references information (id)
);

create table if not exists work_personality
(
    id               int auto_increment
        primary key,
    authors          varchar(255) null,
    number_pages     int          null,
    publication_date date         null,
    work_info        varchar(255) not null,
    work_kind        varchar(255) null,
    work_name        varchar(255) null,
    information_id   int          not null,
    constraint FKajhfxy9e13mlosjhmx9w4cy7c
        foreign key (information_id) references information (id)
);


create table if not exists roles
(
id int auto_increment
primary key,
name varchar(255) null
);

create table if not exists user
(
id int auto_increment
primary key,
email varchar(255) not null,
first_name varchar(255) not null,
last_name varchar(255) not null,
password varchar(255) not null,
username varchar(50) not null,
constraint UK_sb8bbouer5wak8vyiiy4pf2bx
unique (username)
);

create table if not exists user_roles
(
user_id int not null,
role_id int not null,
constraint FK55itppkw3i07do3h7qoclqd4k
foreign key (user_id) references user (id),
constraint FKh8ciramu9cc9q3qcqiv4ue8a6
foreign key (role_id) references roles (id)
);

INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'ффф', null, 'ффффф', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (2, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Baxter', null, 'Wade', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (3, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ryan', null, 'Hewitt', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (4, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Hammett', null, 'Hoover', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (5, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Wesley', null, 'Newman', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (6, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Hamish', null, 'Porter', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (7, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Raphael', null, 'Walsh', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (8, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Thor', null, 'Ruiz', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (9, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kathleen', null, 'Washington', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (10, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Merritt', null, 'Trevino', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (11, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Odysseus', null, 'Schmidt', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (12, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Quinlan', null, 'William', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (13, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Malcolm', null, 'Ellis', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (14, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kirby', null, 'Villarreal', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (15, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kameko', null, 'Beach', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (16, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Salvador', null, 'Underwood', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (17, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Barclay', null, 'Dennis', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (18, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Nash', null, 'Spears', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (19, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Dorothy', null, 'Maddox', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (20, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Guy', null, 'Blanchard', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (21, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Summer', null, 'Rosa', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (22, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Fletcher', null, 'Lewis', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (23, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Colin', null, 'Hardin', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (24, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Quin', null, 'Wilkins', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (25, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Wanda', null, 'Kane', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (26, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Violet', null, 'Merritt', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (27, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Elvis', null, 'Hood', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (28, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Inga', null, 'Olson', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (29, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Alfonso', null, 'Conner', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (30, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Gemma', null, 'Le', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (31, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Nadine', null, 'Atkins', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (32, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ariel', null, 'Dawson', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (33, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Lila', null, 'Short', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (34, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Dorothy', null, 'Small', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (35, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Alec', null, 'Carrillo', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (36, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Christopher', null, 'Potts', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (37, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'May', null, 'Solis', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (38, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Michael', null, 'Moss', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (39, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Quincy', null, 'Baldwin', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (40, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kibo', null, 'Ratliff', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (41, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Jamalia', null, 'Keller', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (42, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Adena', null, 'Mccray', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (43, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Alisa', null, 'Hunter', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (44, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Hedy', null, 'Price', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (45, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Dana', null, 'Hurst', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (46, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ronan', null, 'Berg', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (47, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Micah', null, 'Ray', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (48, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Inez', null, 'Riley', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (49, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Sacha', null, 'Key', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (50, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ferdinand', null, 'Allison', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (51, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Colt', null, 'Sellers', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (52, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Harrison', null, 'Chan', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (53, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kasimir', null, 'Avila', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (54, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Joan', null, 'Watts', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (55, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Oscar', null, 'Savage', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (56, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Tad', null, 'Holmes', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (57, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Aurora', null, 'Russell', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (58, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Chancellor', null, 'Avery', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (59, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Elliott', null, 'Fuentes', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (60, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kermit', null, 'Alexander', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (61, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Lucy', null, 'Michael', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (62, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Jonah', null, 'Mclaughlin', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (63, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Nathaniel', null, 'Watson', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (64, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ezra', null, 'Roman', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (65, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Herrod', null, 'Lamb', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (66, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Alec', null, 'Mckee', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (67, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Lillian', null, 'Snider', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (68, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Phoebe', null, 'Grant', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (69, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Rafael', null, 'Ferguson', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (70, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Amber', null, 'Vaughan', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (71, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'May', null, 'Figueroa', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (72, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Yeo', null, 'Vaughan', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (73, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Caryn', null, 'Jackson', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (74, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Jerry', null, 'Strickland', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (75, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Gail', null, 'Mccullough', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (76, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Stewart', null, 'Gates', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (77, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Jason', null, 'Hobbs', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (78, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Demetria', null, 'Whitfield', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (79, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Hu', null, 'Carey', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (80, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Clark', null, 'Bolton', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (81, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Thomas', null, 'Lambert', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (82, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Jana', null, 'Holloway', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (83, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kameko', null, 'Griffin', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (84, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Zena', null, 'Evans', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (85, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Ulysses', null, 'Odonnell', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (86, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Minerva', null, 'Cantrell', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (87, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kiara', null, 'Evans', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (88, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Charles', null, 'Soto', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (89, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Dalton', null, 'Winters', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (90, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Amity', null, 'Navarro', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (91, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Clementine', null, 'Hopper', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (92, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Mallory', null, 'Kaufman', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (93, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Erin', null, 'Michael', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (94, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Philip', null, 'Pennington', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (95, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Michelle', null, 'Rutledge', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (96, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Oleg', null, 'Emerson', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (97, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Carla', null, 'Solis', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (98, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Katell', null, 'Smith', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (99, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Unity', null, 'Murray', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (100, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Kyla', null, 'Pitts', null, null, null, null, null, null, null, null, null, null);
INSERT INTO famous_people.information (id, achievements, alias, attitude_to_marriage, awards, biography, characteristic, citizenship, confession, country_birth, country_death, date_birth, date_death, education, ethnos, faith, first_name, friends_and_enemies, last_name, links_to_website, member_ship, nationality, occupation, patronymic, place_birth, place_burial, politic, profession, region_birth) VALUES (101, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Reuben', null, 'Wells', null, null, null, null, null, null, null, null, null, null);
